### PR TITLE
Apple Auth added (Firebase Authentication)

### LINKED ISSUE #27: Firebase Authentication
- [ ] Google Auth
- [ ] Apple Auth

### PR DESCRIPTION
**Pull request by Mohitmadhav**
### Related Issue
- Fixes #27.

### Proposed Changes
- Displays error for Android users that they are not an ios user
- Added Apple Authentication code

### Additional Information
- Needs to be tested on an ios device since I didn't have ios, I couldn't do that.

### Checklist
- [ ] Tested
- [ ] No Conflicts
- [x] Change In Code
- [ ] Follows linting rules

### Screenshots
Before this PR            | After this PR
:-----------------------: | :-----------------------:
Screenshot_20210417-143954  | Screenshot_20210418-165208

### CODE REVIEW

**Comment by Mohitmadhav** [comment]
> @Mohitmadhav Please pull the latest code, and resolve the merge conflicts.

@SapinderSingh @himanshusharma89 all the conflicts are resolved
Now can you check the auth?? If it works then there'll be no need for Codemagic (It's a bit lengthy 😅)

**Comment by himanshusharma89** [comment]
@Mohitmadhav I don't own a XCode, so do it with CodeMagic or I'll do it later

**Comment by himanshusharma89** [comment]
@Mohitmadhav Don't push in the same PR, create new brach for every new task

**Comment by Rishabh510** [comment]
> @Mohitmadhav Don't push in the same PR, create new brach for every new task. And do git pull before pushing

Are we doing the iOS part along with the Android part or we'll do that after the prototype for Android is complete?
I suggest we create a separate branch for iOS part temporarily so that any iOS related changes can be fetched from there itself. Whats your opinion @himanshusharma89

**Comment by himanshusharma89** [comment]
@Rishabh510 There is no need to create a separate branch for iOS, all the changes need to be done in the ios folder. The concepts logic will stay in lib.

**Pull request closed without merging**
