### PR TITLE
App Drawer Added

### LINKED ISSUE #26: App Drawer
Create an app drawer in the dashboard and invoke it from the home using Global Scaffold State key

### PR DESCRIPTION
**Pull request by diksh735**
closes #26 
drawer

### CODE REVIEW

**Comment by diksh735** [comment]
I hope its fine now, to resolve everything I just forked the repository again to make sure no conflicts happen this time. 
And made a pull request from a branch other than master branch.

**Comment by himanshusharma89** [comment]
@diksh735 It looks good now, but you don't have to fork it, again and again, use git CLI to rebase the code. Also, can you just add tiles in the drawer with a retro theme? Like About, Cart, Wishlist, Products, & Log Out text-tiles in a ListView

**Comment by diksh735** [comment]
Yes, I can do that

**Comment by himanshusharma89** [comment]
@diksh735 can you add the image of the updated drawer?

**Comment by diksh735** [comment]
DrawerListTiles

**Comment by diksh735** [comment]
I did not know about the Icons you used so I used the Material Icons itself and the pixer font family which you have used in your App

**Comment by himanshusharma89** [comment]
Okay no issues @diksh735

**Comment by himanshusharma89** [comment]
@diksh735 Try to create different files for each view next time.

**Comment by diksh735** [comment]
Sure !

**Pull request merged**
