### PR TITLE
docs: added pr label workflow

### LINKED ISSUE #83: PR Labeller
Create a GitHub Action workflow to label the PR with `GSSOC21` tag

### PR DESCRIPTION
**Pull request by aayushbisen**
### Related Issue
- Fixes #83  .

### Proposed Changes
- Added GitHub Actions workflow to add `GSSOC21` label in PRs.

### Checklist
- [x] Tested
- [x] No Conflicts
- [x] Change In Code
- [ ] Change In Documentation

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@aayushbisen Check this t resolve the GitHub Token issue: https://github.com/housepower/ClickHouse-Native-JDBC/issues/292#issue-783173706

**Comment by aayushbisen** [comment]
> @aayushbisen Check this t resolve the GitHub Token issue: [housepower/ClickHouse-Native-JDBC#292 (comment)](https://github.com/housepower/ClickHouse-Native-JDBC/issues/292#issue-783173706)

Already made the change in second commit. But still this PR isn't labelled yet 😕

**Comment by himanshusharma89** [comment]
@aayushbisen did you tested it in your forked repo?

**Comment by aayushbisen** [comment]
Yes I tested the action it is working in my fork.

image

image

image

**Comment by aayushbisen** [comment]
Ran multiple tests, the action seems to be working.

The action is triggering on `pull_request` and is not firing at `pull_request_target` event.

image

**Comment by himanshusharma89** [comment]
Okay @aayushbisen, let's search for a solution for that

**Comment by aayushbisen** [comment]
I think `pull_request_target` event is triggered only when the PR is opened on the base repo, that's why it is not working for me.

See this: https://github.com/nf-core/tools/issues/765

How can we test this action?

**Comment by himanshusharma89** [comment]
@aayushbisen I'll check the provided link, in the mean-time, you can check this: https://github.com/smaranjitghose/girlscript_app/tree/master/.github

**Comment by aayushbisen** [comment]
> @aayushbisen I'll check the provided link, in the mean-time, you can check this: https://github.com/smaranjitghose/girlscript_app/tree/master/.github

I checked the workflows here and the pr labeler is using `labeler` action which labels according to changed file paths. I think that's not really helpful in this use case.

For now, we can simply trigger the action on `pull_request` event to label the PRs.

**Comment by himanshusharma89** [comment]
> I think `pull_request_target` event is triggered only when the PR is opened on the base repo, that's why it is not working for me.
> 
> See this: [nf-core/tools#765](https://github.com/nf-core/tools/issues/765)
> 
> How can we test this action?

I am merging this PR and testing it.

**Comment by himanshusharma89** [comment]
Working

**Comment by aayushbisen** [comment]
Great 🎉

**Pull request merged**
