### PR TITLE
Added Email Auth(#27)

### PR DESCRIPTION
**Pull request by puru-ganda**

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@puru-ganda Update the PR as per the PR template and do attach a video of the auth too.

**Comment by puru-ganda** [comment]
> @puru-ganda Update the PR as per the PR template and do attach a video of the auth too.

@himanshusharma89 should i also need to implement sign up functionality??

**Comment by puru-ganda** [comment]
@himanshusharma89 can you please add a EMAIL and PASSWORD to the firebase console and provide that details to me so that I can use that for verification in demo video

**Comment by himanshusharma89** [comment]
@puru-ganda Email auth is enabled now.

**Comment by puru-ganda** [comment]
> @puru-ganda Email auth is enabled now.

@himanshusharma89 okay, but I need a added USER email and password so that I can verify the email auth functionality

**Comment by himanshusharma89** [comment]
> @himanshusharma89 okay, but I need a added USER email and password so that I can verify the email auth functionality

Yeah, I almost forgot it. I'll create an issue for that and then you can start implementing it on that screen

**Comment by puru-ganda** [comment]
> > @himanshusharma89 okay, but I need a added USER email and password so that I can verify the email auth functionality
> 
> Yeah, I almost forgot it. I'll create an issue for that and then you can start implementing it on that screen

okay

**Comment by himanshusharma89** [comment]
@puru-ganda Pull the latest code, the screen is added. You can start working on it

**Comment by puru-ganda** [comment]
> @puru-ganda Pull the latest code, the screen is added. You can start working on it

sure

**Comment by Rishabh510** [comment]
@himanshusharma89 we can link this to an issue for it to get tracked

**Comment by puru-ganda** [comment]
@himanshusharma89 I have implemented the Email Auth functionality to Login and Signup screen but due to some problem in my local machine I am unable to push the updates to this PR so can I close this PR and open a NEW one.

**Comment by puru-ganda** [comment]
#### Related Issue
  - Fixes #27  .
#### Proposed Changes
- Added User Email Auth in login screen
- Added User Registration using email and password in sign up screen
- Added logout functionality
- Added cutom_dialogalert widget for Auth functionality
#### Checklist
 - [x] Tested
 - [x] No Conflicts
 - [x] Change In Code
 - [ ] Change In Documentation

#### Demo

https://user-images.githubusercontent.com/48974290/112064328-cad98c00-8b88-11eb-95c9-b906a6abeb3c.mp4

**Comment by himanshusharma89** [comment]
We need a few changes here:

- [ ] Show the error below the fields not in a Dialog
- [ ] Don't use the same controller for both the text fields
- [ ] Squash the commits: https://github.com/wprig/wprig/wiki/How-to-squash-commits
- [ ] Follow the lining rules, especially in signup.dart

**Comment by himanshusharma89** [comment]
@puru-ganda Pull the latest code before working on it.

**Comment by puru-ganda** [comment]
> @puru-ganda Pull the latest code before working on it.

okay

**Comment by himanshusharma89** [comment]
@puru-ganda 30 files got changed for this PR, I think you didn't rebase your code perfectly, try it again. And also implement the email auth inside the AuthService class.

**Comment by puru-ganda** [comment]
> @puru-ganda 30 files got changed for this PR, I think you didn't rebase your code perfectly, try it again. And also implement the email auth inside the AuthService class.

Yes I was facing some issues with merge, I will implement email auth soon.

**Comment by puru-ganda** [comment]
@himanshusharma89 Can I create a new PR as I am facing issues with the current local branch EmailAuth and close this. So I have to make a new branch and implement Email Auth on that branch.

**Comment by himanshusharma89** [comment]
> @himanshusharma89 Can I create a new PR and close this one as I am facing issues with the current local branch EmailAuth.
> because I need to create a new branch and implement email auth on that.

I don't encourage it, but go ahead, if you are not able to perform the task.

**Comment by puru-ganda** [comment]
> > @himanshusharma89 Can I create a new PR and close this one as I am facing issues with the current local branch EmailAuth.
> > because I need to create a new branch and implement email auth on that.
> 
> I don't encourage it, but go ahead, if you are not able to perform the task.

okay

**Pull request closed without merging**
