### PR TITLE
Wishlist screen 

### LINKED ISSUE #35: Wishlist Screen
Create a retro theme based UI for the Wishlist screen

### PR DESCRIPTION
**Pull request by ThatOneTallKid**
### Related Issue: Wishlist Screen
- Fixed #35 .

### Proposed Changes
- Created ```Wishlist.dart``` in the views folder to create a new screen that contains wishlist
- Assigned Navigator in ```drawer_item.dart``` to navigate to Wishlist  Screen

### Additional Information
- The Change suggests a Wishlist screen as proposed by the issue #35 .

### Checklist
- [x] Tested
- [x] No Conflicts
- [x] Change In Code
- [ ] Change In Documentation

### Screenshots
Before this PR            | After this PR
:-----------------------: | :-----------------------:
** This is a new Screen** | WhatsApp Image 2021-03-14 at 5 09 47 PM

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@ThatOneTallKid Can you squash the commits?
https://github.com/wprig/wprig/wiki/How-to-squash-commits

**Comment by ThatOneTallKid** [comment]
Yes

**Comment by himanshusharma89** [comment]
@ThatOneTallKid This PR is good, why did you close it?

**Comment by himanshusharma89** [comment]
And the commits are squashed too.

**Comment by ThatOneTallKid** [comment]
Oh! I made another Updated PR , syncing up with the master.

**Comment by ThatOneTallKid** [comment]
You can check #129

**Comment by himanshusharma89** [comment]
I didn't notice any issue with this PR, any changes between this one and the other one? @ThatOneTallKid

**Comment by ThatOneTallKid** [comment]
I pulled the latest code after this PR. So that's why I closed it. I am still learning git

**Comment by ThatOneTallKid** [comment]
Did I do something wrong?

**Comment by himanshusharma89** [comment]
Nothing, this PR was good, you did well. But let it be closed I'll merge the other one.

**Pull request closed without merging**
