### PR TITLE
Login UI Update

### PR DESCRIPTION
**Pull request by AksV73**
### Related Issue
- Fixes # .
Login screen overflowing
### Proposed Changes
- Resized widgets
- Added a scroll

### Checklist
- [x] Tested
- [x] No Conflicts
- [x] Change In Code
- [ ] Change In Documentation
- [x] Follows linting rules
Screenshot_20210327-125350

### Screenshots
Before this PR            | After this PR
:-----------------------: | :-----------------------:
** Original Screenshot ** | ** Updated Screenshot **

### CODE REVIEW

**Comment by AksV73** [comment]
Is the space between the text fields and buttons alright ?

**Comment by himanshusharma89** [comment]
@AksV73 Why did you created new PR?

**Comment by AksV73** [comment]
@himanshusharma89  i wasn't able to push the changes made. Really sorry for this.

**Comment by himanshusharma89** [comment]
> @himanshusharma89 i wasn't able to push the changes made. Really sorry for this.

Next time follow the issues template with the issue id in Fixes and don't create new PR. I'll merge this one for now.

**Comment by himanshusharma89** [comment]
Also @AksV73 squash the commits: https://github.com/wprig/wprig/wiki/How-to-squash-commits

**Comment by AksV73** [comment]
@himanshusharma89  Thank you!
Will look into it and will not repeat the mistake.

**Comment by AksV73** [comment]
@himanshusharma89 is it necessary for me to squash the commit messages ?

**Comment by himanshusharma89** [comment]
> @himanshusharma89 is it necessary for me to squash the commit messages ?

For such a minor issue, we don't need more than 1 commit

**Comment by AksV73** [comment]
> > @himanshusharma89 is it necessary for me to squash the commit messages ?
> 
> For such a minor issue, we don't need more than 1 commit

Ok, will work on squashing

**Comment by himanshusharma89** [comment]
@Alifbhanvadiya14 Any update?

**Comment by AksV73** [comment]
I haven't been able to squash. I tried my best

**Pull request merged**
