### PR TITLE
Added Email Validation using Forms and RegExp, Fixes issue #177

### LINKED ISSUE #177: Login and Sign Credentails Validation
Use RegEx to validate the email using TextFormField features.

# Discussion 🗣
Features required to indicate user if the email is not valid.

## Detailed Description
Display the error below the centre UI (Don't show the error below the TextFormField). Also, if the email is correct after don't display the error. (user TextFormField features for that)

### PR DESCRIPTION
**Pull request by abhishek7997**
### Related Issue
- Fixes #177 

### Proposed Changes
- Changed userEmailValidation([]) in auth_service.dart
- Change code inside validator of form field in signup_view.dart and login_view.dart
- Email validation is done via RegExp() and SnackBar is used to show any error

### Additional Information
- Changed return type of userEmailValidation([]) from String to boolean.

### Checklist
- [x] Tested
- [x] No Conflicts
- [x] Change In Code
- [ ] Change In Documentation
- [x] Follows linting rules

### Screenshots
Before this PR            | After this PR
:-----------------------: | :-----------------------:
** Original Screenshot ** | ** Updated Screenshot **
:-----------------------: | :-----------------------:
Screenshot_1619932403  |  Screenshot_1619932325
:-----------------------: | :-----------------------:
Screenshot_1619932362 |  Screenshot_1619932306

### CODE REVIEW

**Comment by abhishek7997** [comment]
@himanshusharma89 Please review and if it is okay, merge this PR.

**Comment by himanshusharma89** [comment]
As mentioned in the PR, show the error message below the form, the current validator doesn't look with the textformfield. And we don't need SnackBar here.

**Comment by abhishek7997** [comment]
@himanshusharma89 Could you please elaborate on what is exactly needed?

**Comment by himanshusharma89** [comment]
@abhishek7997 Why did you closed this PR? Are you not familiar with git?

**Comment by himanshusharma89** [comment]
And before contributing, did you read the contributing or the pinned messages in the Discord server?

**Comment by abhishek7997** [comment]
I was trying to restore the changes made, but I accidently closed the PR using git fetch and force push.

**Comment by abhishek7997** [comment]
> 
> 
> And before contributing, did you read the contributing or the pinned messages in the Discord server?

No, I will read it now.

**Comment by abhishek7997** [comment]
@himanshusharma89 Is it possible for you to re open this PR?

**Comment by himanshusharma89** [comment]
@abhishek7997 I cannot re-open it. If you are not able to re-open this PR from your side, then the force push caused the issue.

**Comment by abhishek7997** [comment]
@himanshusharma89 Please help. What should I do next?

**Comment by himanshusharma89** [comment]
Okay, do some changes in the master branch and commit them. This might prompt me to open the PR. Also, let this PR be, create a new branch, don't use master to create PR

**Comment by abhishek7997** [comment]
@himanshusharma89 Should I just make some dummy changes for now? Or should I write code that fixes this issue, and then do the commit?

**Comment by himanshusharma89** [comment]
@abhishek7997 Create a new branch and resolve the assigned issue, don't work on the master branch. Create a new PR from the new branch after working on the issue.

**Comment by abhishek7997** [comment]
@himanshusharma89 That I will do. But right now should I do some changes in the master branch that allows you to re open the PR first? or make changes in the new branch?

**Comment by himanshusharma89** [comment]
> Okay, do some changes in the master branch and commit them. This might prompt me to open the PR. Also, let this PR be, create a new branch, don't use master to create PR

@abhishek7997 As I told you already, let this PR be. You created this PR from master branch, so no need to work on this branch.

**Comment by abhishek7997** [comment]
Okay

**Comment by himanshusharma89** [comment]
@abhishek7997 I told you, don't work on this PR, it is on your master branch. Create a new PR from different branch.

> @abhishek7997 Create a new branch and resolve the assigned issue, don't work on the master branch. Create a new PR from the new branch after working on the issue.

**Comment by abhishek7997** [comment]
> 
> 
> @abhishek7997 I told you, don't work on this PR, it is on your master branch. Create a new PR from different branch.
> 
> > @abhishek7997 Create a new branch and resolve the assigned issue, don't work on the master branch. Create a new PR from the new branch after working on the issue.

Okay, I have created a new branch.
Will work on that.

**Comment by himanshusharma89** [comment]
Okay

**Pull request closed without merging**
