### PR TITLE
Keyboard not hiding on user tap issue is now fixed

### LINKED ISSUE #37: Hide Keyboard
Change the focus to hide the keyboard, whenever the user taps on the screen other than the keyboard

### PR DESCRIPTION
**Pull request by abhishek7997**
Original Issue:
When the keyboard pops up when tapping on the search bar, I cannot be made hidden by tapping on the screen. The only way was to use the back button.

Closes #37 

Fix:
Added a gesture detector in home.dart and one in dashboard.dart

Video of the fix:
https://user-images.githubusercontent.com/68701271/110464931-c7122800-80f9-11eb-9fb2-57520334f4c6.mp4

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@abhishek7997 Instead of creating 2 gesture detectors in different files, update the MaterailApp with the GestureDetector in main.dart. Some thing like this: https://github.com/himanshusharma89/Flutter-Blog-App/blob/master/lib/main.dart

**Comment by abhishek7997** [comment]
Sure,

I will look into it and see whether that fixes the issue.

Regards
M.Abhishek

**Comment by abhishek7997** [comment]
Yes, this works.
So, how should I make a PR.
I have made a PR before. Should I redownload the project, then make this
change?
Should I make a new PR?

Regards
M.Abhishek

**Comment by himanshusharma89** [comment]
No @abhishek7997, you just need to update the code in your machine and push it to your forked repo, it'll update this PR automatically. And next time try to create a PR from a different branch.

**Comment by abhishek7997** [comment]
Ok, I will do that.

Thanks once again.

**Comment by abhishek7997** [comment]
Hello sir,
I have pushed the updated files to my fork using git push. Will the PR be
updated, or should I issue a new PR?

Regards
M.Abhishek

**Comment by himanshusharma89** [comment]
@abhishek7997 The PR is updated but can you tell me why home.dart is updated? For this issue only main.dart is required to be changed. Can you remove the home.dart update and rebase your code to a single commit?

**Comment by abhishek7997** [comment]
home.dart was updated because I removed gesture detector from there.

**Comment by abhishek7997** [comment]
Those file were also updated from where I removed gesture detector, just like you asked. and added it into main.dart. Thats why the files were updated.

**Comment by abhishek7997** [comment]
Please tell me how do I remove home.dart update.

**Comment by abhishek7997** [comment]
home.dart was updated because I removed gesture detector from there.
Those file were also updated from where I removed gesture detector, just
like you asked. and added it into main.dart. Thats why the files were
updated.

Please tell me how do I remove home.dart update.

**Comment by himanshusharma89** [comment]
@abhishek7997 You need to undo your code, or you can delete the home and dashboard file and do a git pull, it'll update the files to default. And then push it to your forked repo. Also, did you tested the new implementation of the keyboard?

**Comment by abhishek7997** [comment]
Can I fork and clone the original repository? And then make the single change to main.dart?

**Comment by himanshusharma89** [comment]
Yes, you are supposed to fork the repo and update the forked repo and create a PR.

**Comment by abhishek7997** [comment]
Github is asking for a new pull request. What should I do?
I deleted the old clone nd re-downloaded after forking.

**Comment by abhishek7997** [comment]
Please help me.

I have mistakenly created another PR. Now there are two PR's. The old one
has the GSSOC label whereas the new one does not.
Please tell me what should I do now?

[image: image.png]

Regards,
M.Abhishek

**Comment by abhishek7997** [comment]
There are two PR's. The old one has the GSSOC label and I am the assignee
(it is shown there). Whereas the new one is just a regular PR, with no
GSSOC label. So, which one should I delete? Will it affect my score?

Regards,
M.Abhishek

**Pull request closed without merging**
