### PR TITLE
Added the change username and password screen

### LINKED ISSUE #38: Settings Screen
Create Settings Screen containing:

- [x] Your Orders Screen
- [x] Change User Name/Password Screen
- [x] FAQs Screen 
- [x] Log Out Button 
- [x] Manage Address
- [ ] Notification(enable or disable): @anotherwebguy 
- [x] T&C
- [x] GitHub Repo Link Button: Open the in-app web view

### PR DESCRIPTION
**Pull request by Samdid**
### Related Issue
- Fixes #38  .

### Proposed Changes
- added the change username and password screen

### Additional Information
- Any additional information about the change

### Checklist
- [x] Tested
- [x] No Conflicts
- [x] Change In Code
- [ ] Change In Documentation
- [x] Follows linting rules

### Screenshots
After this PR
:-----------------------:
** Updated Screenshot **
Screenshot_1616438311

### CODE REVIEW

**Comment by Samdid** [comment]
@himanshusharma89 Please review and merge this PR.

**Comment by himanshusharma89** [comment]
@Samdid Can you not ignore the warnings and resolve them?

**Comment by Samdid** [comment]
> @Samdid Can you not ignore the warnings and resolve them?

I didn't found any warning

**Comment by himanshusharma89** [comment]
> I didn't found any warning

You ignored all of them, remove all the `// ignore` comments and resolve the warnings.

**Comment by Samdid** [comment]
> > I didn't found any warning
> 
> You ignored all of them, remove all the `// ignore` comments and resolve the warnings.

Okay

**Comment by himanshusharma89** [comment]
@Samdid  Pull the latest code before working on it.

**Comment by Samdid** [comment]
> @Samdid Pull the latest code before working on it.

Do I have to remove all the warnings or just from the file which I have created?

**Comment by himanshusharma89** [comment]
> > @Samdid Pull the latest code before working on it.
> 
> Do I have to remove all the warnings or just from the file which I have created?

From your files only.

**Comment by Samdid** [comment]
> > > @Samdid Pull the latest code before working on it.
> > 
> > 
> > Do I have to remove all the warnings or just from the file which I have created?
> 
> From your files only.

Okay👍

**Comment by Samdid** [comment]
@himanshusharma89 resolved all the warnings and also pulled the latest code

**Pull request merged**
