### PR TITLE
Added safe area widget

### LINKED ISSUE #103: Adding SafeArea widget on home.dart to avoid cutting off of screen
Currently there is no SafeArea widget because of which there is a possibility of drawer button getting cut by the top bar that show battery percentage on phones with smaller screen size.

### PR DESCRIPTION
**Pull request by D-Ajay-Kumar**
### Related Issue
- Fixes #103 

### Proposed Changes
- Added SafeArea widget to the app

### Checklist
- [x] Tested
- [x] No Conflicts
- [x] Change In Code
- [x] Change In Documentation
- [x] Follows linting rules

### CODE REVIEW

**Comment by D-Ajay-Kumar** [comment]
Resolved the conflicts @himanshusharma89

**Comment by himanshusharma89** [comment]
@D-Ajay-Kumar Do we always need SafeArea for any new Scaffold Widget? or one-time using SafeArea works fine?

**Comment by himanshusharma89** [comment]
Also @D-Ajay-Kumar I have seen a whole new screen in this PR, can you rebase your code again.

**Comment by D-Ajay-Kumar** [comment]
> @D-Ajay-Kumar Do we always need SafeArea for any new Scaffold Widget? or one-time using SafeArea works fine?

If we use SafeArea on the topmost level then even the app bar's of scaffolds will get wrapped inside the safe area which is not usually done, only the body of every scaffold needs to be inside the safe area otherwise it gets uneven and ugly. To wrap only the body and maintain consistency a SafeArea is required everywhere.

**Comment by D-Ajay-Kumar** [comment]
> Also @D-Ajay-Kumar I have seen a whole new screen in this PR, can you rebase your code again.

git rebase upstream/master

Right? And then commit again?

**Comment by himanshusharma89** [comment]
> git rebase upstream/master

No, you upstream will be your forked repo, you need to rebase the PR with my repo origin. You can check your remote using git remote -v. If my repo with my HTTPS is not added add it in your remote and then do git rebase origin master

**Comment by D-Ajay-Kumar** [comment]
This is how it is currently. I thought origin is the forked repo on my GitHub where I commit changes, do I have it all wrong?

remote

**Comment by himanshusharma89** [comment]
@D-Ajay-Kumar Oh so upstream is mine, so you can do one thing pull the latest code from upstream in your master branch (git pull upstream master) after that checkout to your branch and do git rebase master, (resolve and continue).
If doesn't work do git merge master

**Comment by D-Ajay-Kumar** [comment]
I...... have a slight doubt that it didn't work the way it was supposed to be. Could you please confirm it for me?

**Comment by himanshusharma89** [comment]
Most of the files changes in thus PR already exists. Did you comiited your code on every conflict? If so, you are not supposed to do that

**Comment by D-Ajay-Kumar** [comment]
I rebased my code with master after pulling from upstream so it showed me a bunch of conflicts and after resolving them I commited them. Should I not stage those files in the first place?

**Comment by himanshusharma89** [comment]
> I rebased my code with master after pulling from upstream so it showed me a bunch of conflicts and after resolving them I commited them. Should I not stage those files in the first place?

Oh, this is the problem, after resolving a conflict, you just need to add them (git add .) and continue. You should not commit them. 

Now, what you can do, try git reset --hard, if it is possible. If not, you can roll back to your old code where you initially created this PR(check the hash in this PR)

**Comment by himanshusharma89** [comment]
Any update @D-Ajay-Kumar?

**Comment by D-Ajay-Kumar** [comment]
Sorry about the delay, I had a couple of tests in college. Anyhow, this is how the git looks currently. I did the hard reset and this is where it brought me. What should I do next? There aren't anymore conflicts

now

**Comment by himanshusharma89** [comment]
@D-Ajay-Kumar Pull the code again, verify your work on all the screen, then do git push. If the issue still remains, you can do one thing, delete your branch locally and create that exact branch again(this time after pulling the latest code in master) and do your changes and push. No need to close this PR.

**Comment by D-Ajay-Kumar** [comment]
Lemme do the latter

**Comment by D-Ajay-Kumar** [comment]
Sorry for the late work, my college's announced tests all of a sudden. Anyhow, I have made the changes and I see that there seems to be a lot of deletion and addition but it's just that when I hit save on my editor it automatically added indentations and new lines for styling purposes. That's where there seem to be a lot of changes.

**Comment by himanshusharma89** [comment]
@D-Ajay-Kumar Apart from indentations the changes in your PR already exists in this PR. Did you tried to delete your branch, pull the latest code from MY REPO REMOTE (not your forked one) in master and then create the same branch again from the master. After this you can again do your work.

**Comment by D-Ajay-Kumar** [comment]
Yup I deleted the whole branch, pulled latest code from your repo, updated mine, created a new branch with same name, made all the changes again and pushed the changes

**Comment by himanshusharma89** [comment]
@D-Ajay-Kumar Are you using any specific type of code formatter?

**Comment by himanshusharma89** [comment]
Also, if this is the case can you format your code using Shift + Alt + F

**Comment by himanshusharma89** [comment]
@D-Ajay-Kumar Any update? This has taken a lot of time

**Pull request closed without merging**
