### PR TITLE
Aks v

### PR DESCRIPTION
**Pull request by AksV73**
### Related Issue
- Login page overflowing

### Proposed Changes
- Added horizontal scroll
- Resized widgets

- [x]  Tested

- [x] No Conflicts
- [x] Change In Code
- [ ] Change In Documentation
- [x] Follows linting rules

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@AksV73 Can you add the screenshot of the screen here?

**Comment by AksV73** [comment]
[
Screenshot_20210326-222958
](url)

**Comment by himanshusharma89** [comment]
@AksV73 You should add the spacing in between the Text Fields and the buttons(both login and social) also. It is to conjusted.

**Comment by AksV73** [comment]
Sure, will do that and get back.

**Comment by himanshusharma89** [comment]
@AksV73 Can you add the new screenshot?

**Pull request closed without merging**
