### PR TITLE
Fixed the all Renderflex Overflow issue in cart.dart file for all the…

### LINKED ISSUE #33: Cart Screen
Update the UI for the Cart screen

### PR DESCRIPTION
**Pull request by Neha62-lit**
… screens

### Related Issue
- Fixes #33 .

### Proposed Changes
- Added ScreenUtil package for the responsive app.

### Checklist
- [x] Tested
- [x] No Conflicts
- [x] Change In Code
- [ ] Change In Documentation

### Screenshots
 After this PR
** Updated Screenshot **
largeScreen
smallScreen
tabScreen

### CODE REVIEW

**Comment by Neha62-lit** [comment]
@himanshusharma89 Please review and merge this PR.

**Comment by himanshusharma89** [comment]
@Neha62-lit Why did you used Screen Util here and all the widgets that you shifted to Styles are not required, you can just create these methods in Settings but outside the build method which will increase the code readability.

**Comment by Neha62-lit** [comment]
> @Neha62-lit Why did you used Screen Util here and all the widgets that you shifted to Styles are not required, you can just create these methods in Settings but outside the build method which will increase the code readability.

I used ScreenUtil here for responsive app in all devices and different screens. I tried to solve by using Expanded and Flexible Widgets but there are still renderflex overflow issue in screen. Hence I used ScreenUtil Package here.

**Comment by himanshusharma89** [comment]
@Neha62-lit Instead of screen util use MediaQuery on the whole screen.
So, an update in main.dart is not required, no need for that in the PR. Also, the settings page is added, so no need for that also.

**Comment by Neha62-lit** [comment]
> @Neha62-lit Instead of screen util use MediaQuery on the whole screen.
> So, an update in main.dart is not required, no need for that in the PR. Also, the settings page is added, so no need for that also.

Okay!

**Pull request closed without merging**
