### PR TITLE
Home Screen Updated

### LINKED ISSUE #100: Home Screen Update
Update the Home screen for the following:

- [ ] Add never scroll physics in GridView
- [ ] Divide the view into different widgets methods which are being called in the Column inside build method.

# Discussion 🗣
Improve the home screen code by dividing the widgets into different Widget methods. And do resolve the problems in the terminal if it arises.

## Context
For better readability of the code, this needs to be done.

### PR DESCRIPTION
**Pull request by Chirag018**
Fixes #100

Added never scroll physics in GridView.

Divided the view into different widgets/methods which are being called in the Column widget inside build method.

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@Chirag018 Can you update this PR according to the PR template? Attach the screenshot of the screen here and also mention the issue here, like Fixes #issue_number

**Comment by Chirag018** [comment]
Sir directly I have to update the home.dart file

**Comment by Chirag018** [comment]
Sorry Sir but I am confused!

**Comment by Chirag018** [comment]
Screenshot 2021-03-14 at 3 55 27 PM
Screenshot 2021-03-14 at 3 56 17 PM

Fixed#100

**Comment by himanshusharma89** [comment]
@Chirag018 Check this PR #116  you need to update your PR description like that. You can ignore the checklist.

**Comment by Chirag018** [comment]
Fixes #100 

* Added never scroll physics in GridView.

* Divided the view into different widgets/methods which are being called in the Column inside build method.

**Pull request merged**
