### PR TITLE
fix bugs in setting and profile page

### LINKED ISSUE #105: Bug Fix in Code.
# Bug Report 🐛

## Expected Behavior

Code should build properly.

## Current Behavior

 App is not building due to errors in code.

## Possible Solution

 Settings.dart file and Profile.dart have bugs in it. Resolving it will build it.

Please assign this issue to me. @himanshusharma89

### PR DESCRIPTION
**Pull request by RGTechno**
### Related Issue
- Fixes #105 

### Proposed Changes
- Add Named route for setting and profile
- Formatted Settings.dart and Profile.dart file
- Added missing imports

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@RGTechno Attach a screenshot of the screen in this PR

**Comment by RGTechno** [comment]
@himanshusharma89 u mean the screenshot of settings screen?

**Review by Rishabh510 — APPROVED** [review]
LGTM

**Comment by himanshusharma89** [comment]
@RGTechno The icon needs to be positioned on the top right. Do that and I'll merge the PR.

**Comment by RGTechno** [comment]
Ok. I'll fix that. And Should I make a New PR?

**Comment by RGTechno** [comment]
Screenshot_1615552474
Is This OK? @himanshusharma89

**Comment by himanshusharma89** [comment]
@RGTechno You have to use Stack on the Column in the build method and add this Icon with the help of Positioned or Alignment. Check the previous code in which you removed the Positioned widget.

**Comment by anotherwebguy** [comment]
https://user-images.githubusercontent.com/66346161/110941615-a7c80480-835e-11eb-857d-f520b3740801.mp4

i've already resolved this issue should i make a pr? @himanshusharma89

**Comment by anotherwebguy** [comment]
> @RGTechno You have to use Stack on the Column in the build method and add this Icon with the help of Positioned or Alignment. Check the previous code in which you removed the Positioned widget.

yeah i've used stack and positioned widget here

**Comment by himanshusharma89** [comment]
@anotherwebguy Thanks for the update, but the assigned issue should be resolved by the assigned person. He/She can learn a new thing from this. But can you help him out, understanding the issue? You can contact each other on Discord or you guys can wait till tonight, the relic bazaar channel will be public by then.

**Comment by anotherwebguy** [comment]
> @anotherwebguy Thanks for the update, but the assigned issue should be resolved by the assigned person. He/She can learn a new thing from this. But can you help him out, understanding the issue? You can contact each other on Discord or you guys can wait till tonight, the relic bazaar channel will be public by then.

yeah sure i will help him

**Comment by RGTechno** [comment]
Screenshot_1615553751
I have done this. @himanshusharma89

**Comment by himanshusharma89** [comment]
@RGTechno Nothing is changed, and don't commit each file and the code before finalising the changes. Now, you need to squash commits for this PR to be merged.

**Comment by RGTechno** [comment]
@himanshusharma89 I have added the changes to my forked repo. Thanks for all the help.

**Comment by himanshusharma89** [comment]
> @himanshusharma89 I have added the changes to my forked repo. Thanks for all the help.

The issue is not resolved, you only changed the Text widget.

**Comment by himanshusharma89** [comment]
And squash the commits.

**Comment by RGTechno** [comment]
> And squash the commits.

I am not able to squash the commits. Sorry!

**Comment by himanshusharma89** [comment]
> > And squash the commits.
> 
> I am not able to squash the commits. Sorry! Can I delete this PR and Send a new One with only with commit?

No, not required. Check this: https://github.com/wprig/wprig/wiki/How-to-squash-commits

**Comment by RGTechno** [comment]
> > > And squash the commits.
> > 
> > 
> > I am not able to squash the commits. Sorry! Can I delete this PR and Send a new One with only with commit?
> 
> No, not required. Check this: https://github.com/wprig/wprig/wiki/How-to-squash-commits

No I am not able to do this. Maybe delete the PR and send new one with fresh repo OR you may assign to somebody else

**Comment by himanshusharma89** [comment]
The files are still not updated in this PR. I think it is better if someone else handles this. @anotherwebguy Can you do this? If so, do create a PR and make sure commits are not more than. And @RGTechno I would like you to work on any other issue of your liking if possible.

**Comment by anotherwebguy** [comment]
> The files are still not updated in this PR. I think it is better if someone else handles this. @anotherwebguy Can you do this? If so, do create a PR and make sure commits are not more than. And @RGTechno I would like you to work on any other issue of your liking if possible.

Yeah sure i'll do it along with the settings screen layout @himanshusharma89

**Comment by himanshusharma89** [comment]
@anotherwebguy Solve this issue only for now. The layout will be a separate PR.

**Comment by anotherwebguy** [comment]
> @anotherwebguy Solve this issue only for now. The layout will be a separate PR. I need to merge another PR if it is resolved.

Okay i'll create a pr that fixes only this issue

**Comment by RGTechno** [comment]
> The files are still not updated in this PR. I think it is better if someone else handles this. @anotherwebguy Can you do this? If so, do create a PR and make sure commits are not more than. And @RGTechno I would like you to work on any other issue of your liking if possible.

Yeah..Sure I'll work on some other issue.
Thanks for all the help @himanshusharma89.

**Comment by anotherwebguy** [comment]
> @anotherwebguy Solve this issue only for now. The layout will be a separate PR. I need to merge another PR if it is resolved.

hey @himanshusharma89 i've resolved this issue and made the pr

**Pull request closed without merging**
