### PR TITLE
Added widget tests 

### LINKED ISSUE #54: Widget Testing
https://flutter.dev/docs/cookbook/testing/widget/introduction

### PR DESCRIPTION
**Pull request by piyushpradhan**
Fixes #54 

I've added widget tests for : 
- ProductCard
- ProductPage
- BottomNavigationBar
- CartItem
- OrderItem

Please review these changes and kindly tell me what else I need to add to these tests. 
Thank you.

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@piyushpradhan can you show me the terminal with the test result?

**Comment by piyushpradhan** [comment]
Sure.

Here's the complete VS Code window
image

Here's the terminal 
image

**Comment by himanshusharma89** [comment]
@piyushpradhan Next time update the PR according to the template.

**Comment by piyushpradhan** [comment]
Sure @himanshusharma89. I'll keep that in mind.

**Pull request merged**
