### PR TITLE
Added in app web view for github repository link

### LINKED ISSUE #38: Settings Screen
Create Settings Screen containing:

- [x] Your Orders Screen
- [x] Change User Name/Password Screen
- [x] FAQs Screen 
- [x] Log Out Button 
- [x] Manage Address
- [ ] Notification(enable or disable): @anotherwebguy 
- [x] T&C
- [x] GitHub Repo Link Button: Open the in-app web view

### PR DESCRIPTION
**Pull request by ShrutiJ-01**
### Related Issue
- Fixes #38 GitHub Repo Link Button: Open the in-app web view .

### Proposed Changes
- Add in-app web view to the app for opening Github Repository.

### Additional Information
- Used package webview_flutter for in-app webview

### Checklist
- [x] Tested
- [x] No Conflicts
- [x] Change In Code
- [ ] Change In Documentation
- [x] Follows linting rules

### Screenshots
Before this PR      
** Original Screenshot **
      
webview previous
 
 After this PR

** Updated Screenshot **

webview

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@ShrutiJ-01 can you resolve the conflicts, I'll merge this PR

**Comment by ShrutiJ-01** [comment]
@himanshusharma89 Yes 👍

**Comment by himanshusharma89** [comment]
> @himanshusharma89 Yes 👍

Let me know when you are done with this.

**Comment by himanshusharma89** [comment]
@ShrutiJ-01  Any update?

**Comment by ShrutiJ-01** [comment]
@himanshusharma89  Extremely sorry about the delay! I have resolved the conflicts

**Pull request merged**
