### PR TITLE
added code for faqs screen

### LINKED ISSUE #38: Settings Screen
Create Settings Screen containing:

- [x] Your Orders Screen
- [x] Change User Name/Password Screen
- [x] FAQs Screen 
- [x] Log Out Button 
- [x] Manage Address
- [ ] Notification(enable or disable): @anotherwebguy 
- [x] T&C
- [x] GitHub Repo Link Button: Open the in-app web view

### PR DESCRIPTION
**Pull request by anotherwebguy**
### Related Issue
- Fixes # 38  .

### Proposed Changes
- Added pdf of FAQs
- used advance pdf viewer to display pdf 
- vertical scrolling

### Checklist
- [x] Tested
- [x] No Conflicts
- [x] Change In Code
- [ ] Change In Documentation

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@anotherwebguy Can you follow the linting rules and sort out the warning in the Problems section in your terminal. Also, you should remove the Single Child Scroll View, as the Settings screens will be redesigned soon.

**Comment by anotherwebguy** [comment]
> @anotherwebguy Can you follow the linting rules and sort out the warning in the Problems section in your terminal. Also, you should remove the Single Child Scroll View, as the Settings screens will be redesigned soon.

I added the singlechild scroll view since it was throwing renderflex error on my screen

**Comment by anotherwebguy** [comment]
> @anotherwebguy Can you follow the linting rules and sort out the warning in the Problems section in your terminal. Also, you should remove the Single Child Scroll View, as the Settings screens will be redesigned soon.

I'll remove it though

**Comment by himanshusharma89** [comment]
> > @anotherwebguy Can you follow the linting rules and sort out the warning in the Problems section in your terminal. Also, you should remove the Single Child Scroll View, as the Settings screens will be redesigned soon.
> 
> I added the singlechild scroll view since it was throwing renderflex error on my screen

**Comment by anotherwebguy** [comment]
> @anotherwebguy Can you follow the linting rules and sort out the warning in the Problems section in your terminal. Also, you should remove the Single Child Scroll View, as the Settings screens will be redesigned soon.

done with all the changes u asked for @himanshusharma89

**Pull request merged**
