### PR TITLE
Made Settings layout

### LINKED ISSUE #38: Settings Screen
Create Settings Screen containing:

- [x] Your Orders Screen
- [x] Change User Name/Password Screen
- [x] FAQs Screen 
- [x] Log Out Button 
- [x] Manage Address
- [ ] Notification(enable or disable): @anotherwebguy 
- [x] T&C
- [x] GitHub Repo Link Button: Open the in-app web view

### PR DESCRIPTION
**Pull request by anotherwebguy**
### Related Issue
- Fixes # 38 making seetings screen layout
### Proposed Changes
-Made Settings screen layout

### Checklist
- [x] Tested
- [x] No Conflicts
- [x] Change In Code
- [ ] Change In Documentation

### Screenshots
image

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@anotherwebguy Don't create PR from the master branch from next time.

**Comment by anotherwebguy** [comment]
> @anotherwebguy Don't create PR from the master branch from next time.

Yeah i'll keep that in mind

**Comment by anotherwebguy** [comment]
> @anotherwebguy Don't create PR from the master branch from next time.

Now can i work on some other functionality in the settings screen?

**Comment by himanshusharma89** [comment]
> > @anotherwebguy Don't create PR from the master branch from next time.
> 
> Now can i work on some other functionality in the settings screen?

For the functionality to work we need to cover the authentication and other features. For now, we need to focus on the UI

**Comment by anotherwebguy** [comment]
> > > @anotherwebguy Don't create PR from the master branch from next time.
> > 
> > 
> > Now can i work on some other functionality in the settings screen?
> 
> For the functionality to work we need to cover the authentication and other features. For now, we need to focus on the UI

Yeah i mean the ui like i can make the change address screen by providing location picker, the user can choose hi current location to pick or he/she can manually type it

**Comment by himanshusharma89** [comment]
@anotherwebguy Go ahead mention it in the issue, I'll update the description and assign it to you.

**Pull request merged**
