### PR TITLE
Added License, Code of Conduct and Contributing guidelines to README

### LINKED ISSUE #47: Update README
Update the readme to list out the following

- [ ] License
- [ ] Code of conduct
- [ ] Contributing

You can follow these:
- https://github.com/himanshusharma89/flutterx100
- https://github.com/smaranjitghose/girlscript_app

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Closes #47 

README update, added all the things mentioned in the issue by using one of the projects mentioned there as a reference. Please let me know if you want any changes in the PR. Thank you!

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@Saransh-cpp can you add these https://github.com/smaranjitghose/girlscript_app#contribution-guidelines guidelines with steps as mentioned but as per this project.

**Comment by Saransh-cpp** [comment]
> @Saransh-cpp can you add these https://github.com/smaranjitghose/girlscript_app#contribution-guidelines guidelines with steps as mentioned but as per this project.

Yes sure, I'll start working on that

**Comment by himanshusharma89** [comment]
@Saransh-cpp can you also add the Fork and clone images from the steps in the referral link, I have upgraded the issue difficulty as you have covered the whole issue.

**Comment by Saransh-cpp** [comment]
> @Saransh-cpp can you also add the Fork and clone images from the steps in the referral link, I have upgraded the issue difficulty as you have covered the whole issue.

Yes, do you want me to follow a similar pattern for the forking and cloning process and copy the image and GIFs from the reference repository?

**Comment by himanshusharma89** [comment]
> Yes, do you want me to follow a similar pattern for the forking and cloning process and copy the image and GIFs from the reference repository?

Many participants face this fork issue, so you should just copy all the steps and update the command as per this project.

**Pull request merged**
