### PR TITLE
closes #26

### LINKED ISSUE #26: App Drawer
Create an app drawer in the dashboard and invoke it from the home using Global Scaffold State key

### PR DESCRIPTION
**Pull request by diksh735**
Closes #26

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@diksh735 Can you add a gif/image of the Drawer? and you need to use the Closes #issue_number in the PR description.

Also, can you rebase your code so that we cannot see the Hide Keyboard commit?

**Comment by diksh735** [comment]
I actually removed the code for the Hide Keyboard commit before I made this
new PR.
And what image where do you want be to add it ?

**Comment by himanshusharma89** [comment]
@diksh735 Attach the Drawer Image and rebase your code to resolve the conflicts.

**Comment by himanshusharma89** [comment]
@diksh735 I was talking about the image to attach to this PR description. And also why did you delete the lib folder?

**Pull request closed without merging**
