### PR TITLE
Added menu icon to the top right to navigate to the "Settings" screen

### LINKED ISSUE #39: Profile Screen Update
- [ ] Update the current profile screen and show the user details and buttons to navigate to the "Your Orders" and "Wishlist" screen: 
- [x] Add menu icon to the top right to navigate to the "Settings" screen
- [x] Make the screen responsive for any device.

### PR DESCRIPTION
**Pull request by sakshi2707**
Updated profile screen by adding menu icon to the top right . This issue #39 was assigned to me and now is resolved.

### Related Issue
- Fixes # .

### Proposed Changes
- Added menu icon to the top right to navigate to the "Settings" screen

### Additional Information
- Any additional information about the change

### Checklist
- [x] Tested
- [x] No Conflicts
- [x] Change In Code
- [x] Change In Documentation

### CODE REVIEW

**Comment by sakshi2707** [comment]
closes #39 via #97 
Added menu icon in Profile Screen as assigned @himanshusharma89

**Comment by himanshusharma89** [comment]
@sakshi2707 Can you create a new file named settings.dart and shift the Settings Widget from profile to the new file in views. Also resolve this conflict for PR to be merged.

**Comment by himanshusharma89** [comment]
> @himanshusharma89 I've made the respective changes for issue #39

It looks good but you need to update your code to resolve the conflicts, do git pull once and resolve the conflicts. Also, you don't need to commit every file on an update, you need to commit once when the task is done. Try to squash the commits to one. If you face any issue do let me know.

**Comment by sakshi2707** [comment]
I've resolved all the conflicts. I'm not able to squash the commits into one as I'm a newbie. Please do merge it like this,if possible. Thankyou

**Comment by himanshusharma89** [comment]
> @himanshusharma89 I've resolved all the conflicts. I'm not able to squash the commits into one as I'm a newbie. Please do merge it like this,if possible. Thankyou

Okay, I'll do that for now, but next time make sure to have not more than 2 commits.

**Comment by himanshusharma89** [comment]
> @himanshusharma89 I've resolved all the conflicts. I'm not able to squash the commits into one as I'm a newbie. Please do merge it like this,if possible. Thankyou

Before merging can you add the screenshot of the screen, it was mentioned in the PR to do so.

**Comment by sakshi2707** [comment]
> > @himanshusharma89 I've resolved all the conflicts. I'm not able to squash the commits into one as I'm a newbie. Please do merge it like this,if possible. Thankyou
> 
> Before merging can you add the screenshot of the screen, it was mentioned in the PR to do so.
Actually I have removed the project from my system now. I forgot to take a screenshot, by mistake., sorry for that.
Now I tried to clone the project again, so there are some SDK versions issue coming.

So it would be great if you merge my PR . Thankyou

**Comment by himanshusharma89** [comment]
@sakshi2707 Make sure to fix the issue before pushing something next time.

**Pull request merged**
