### PR TITLE
Added Email Validation using RegExp(), Fixes issue #177

### LINKED ISSUE #177: Login and Sign Credentails Validation
Use RegEx to validate the email using TextFormField features.

# Discussion 🗣
Features required to indicate user if the email is not valid.

## Detailed Description
Display the error below the centre UI (Don't show the error below the TextFormField). Also, if the email is correct after don't display the error. (user TextFormField features for that)

### PR DESCRIPTION
**Pull request by abhishek7997**
### Related Issue
- Fixes #177 

### Proposed Changes
- Changed userEmailValidation([]) in auth_service.dart
- Change code inside validator of form field in signup_view.dart and login_view.dart
- Email validation is done via RegExp()

### Additional Information
- Added checkEmailValidity() to auth_service.dart

### Checklist
- [x] Tested
- [x] No Conflicts
- [x] Change In Code
- [ ] Change In Documentation
- [x] Follows linting rules

### Screenshots
Before this PR            | After this PR
:-----------------------: | :-----------------------:
Screenshot_1619932384 | Screenshot_1619949902
Screenshot_1619932392 | Screenshot_1619949921

### CODE REVIEW

**Comment by abhishek7997** [comment]
@himanshusharma89 Please check the new PR.

**Comment by himanshusharma89** [comment]
@abhishek7997 Can you remove the required validator, and display thee issue below

**Comment by abhishek7997** [comment]
> @abhishek7997 Can you remove the required validator, and display thee issue below

Should I do it only for the email? OR should I do it for the password as well?

**Comment by abhishek7997** [comment]
> @abhishek7997 Can you remove the required validator, and display thee issue below

Should I do it only for the email? OR should I do it for the password as well?

**Comment by abhishek7997** [comment]
@himanshusharma89 Can you tell me how do I resolve the merge conflicts?
Right now there is a conflict with login_view.dart
image

**Comment by himanshusharma89** [comment]
@abhishek7997 In your branch, do git pull origin master, origin should be the remote URL of my repository. You can check the remote URL by git remote -v.

**Comment by abhishek7997** [comment]
> @abhishek7997 In your branch, do git pull origin master, origin should be the remote URL of my repository. You can check the remote URL by git remote -v.

$ git remote -v
origin  https://github.com/abhishek7997/relic_bazaar.git (fetch)
origin  https://github.com/abhishek7997/relic_bazaar.git (push)
upstream        https://github.com/himanshusharma89/relic_bazaar.git (fetch)
upstream        https://github.com/himanshusharma89/relic_bazaar.git (push)

Now, should I use upstream or origin?

**Comment by abhishek7997** [comment]
@himanshusharma89 What should I do with this?

image

Should I use the github browser interface to remove conflict?

**Comment by himanshusharma89** [comment]
@abhishek7997 You need to resolve the issue from your IDE, check the latest code and remove the text with red squiggly  lines

**Comment by abhishek7997** [comment]
@himanshusharma89 Please check it now.

**Comment by abhishek7997** [comment]
@himanshusharma89 I am getting merge conflicts even now, I don't know how to resolve it. I tried updating the fork and making changes, but the error is still there.

**Comment by himanshusharma89** [comment]
> @himanshusharma89 I am getting merge conflicts even now, I don't know how to resolve it. I tried updating the fork and making changes, but the error is still there.

You need to pull the latest code from this repository, make sure it is added as an remote url

**Comment by abhishek7997** [comment]
@himanshusharma89 I tried.

$ git remote -v
origin https://github.com/abhishek7997/relic_bazaar.git (fetch)
origin https://github.com/abhishek7997/relic_bazaar.git (push)
upstream https://github.com/himanshusharma89/relic_bazaar.git (fetch)
upstream https://github.com/himanshusharma89/relic_bazaar.git (push)

I used git pull upstream

**Comment by himanshusharma89** [comment]
@abhishek7997 Do git pull upstream master and resolve the conflicts.

**Comment by abhishek7997** [comment]
@himanshusharma89 I ran the command. This is the output:

$ git pull upstream master
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 32 (delta 26), reused 21 (delta 17), pack-reused 0
Unpacking objects: 100% (32/32), 7.66 KiB | 61.00 KiB/s, done.
From https://github.com/himanshusharma89/relic_bazaar
 * branch            master     -> FETCH_HEAD
   151c914..58e6463  master     -> upstream/master
Auto-merging lib/views/auth/signup_view.dart
CONFLICT (content): Merge conflict in lib/views/auth/signup_view.dart
Auto-merging lib/views/auth/login_view.dart
CONFLICT (content): Merge conflict in lib/views/auth/login_view.dart
Automatic merge failed; fix conflicts and then commit the result.

**Comment by abhishek7997** [comment]
@himanshusharma89 Okay.
I am working on it.

**Comment by abhishek7997** [comment]
@himanshusharma89 Please check now.

**Comment by himanshusharma89** [comment]
@abhishek7997 Can you attach a gif here, in this PR.

**Comment by abhishek7997** [comment]
@himanshusharma89 Here is the GIF.
issue177

**Pull request closed without merging**
