### PR TITLE
Integrated razorpay

### PR DESCRIPTION
**Pull request by nb9960**
@himanshusharma89 PTAL, on pressing 'payment & address' button in the payment window, Razorpay window is displayed and on success, user is navigated to the payment success screen.

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@nb9960 can you attach gif/images of the screens?

**Comment by nb9960** [comment]
> @nb9960 can you attach gif/images of the screens?


https://user-images.githubusercontent.com/63557873/110285451-470c9500-8009-11eb-9005-05f77903191e.mp4

**Comment by himanshusharma89** [comment]
Perfect!, Let me share with you the test keys of Razorpay

**Comment by himanshusharma89** [comment]
> Perfect!, Let me share with you the test keys of Razorpay

Instead of sharing, I'll add it myself.

**Comment by himanshusharma89** [comment]
@nb9960 Check the issue comment to add the rules and test it with the release build of the app

**Comment by himanshusharma89** [comment]
Closes #24

**Pull request merged**
