### PR TITLE
Added T&C Screen Issue #38

### PR DESCRIPTION
**Pull request by SapinderSingh**
### Related Issue
- Fixes # 38.

### Proposed Changes
1. Added T&C Screen
1. Route for the screen added and linked.

### Checklist
- [X] Tested
- [X] No Conflicts
- [X] Change In Code
- [X] Follows linting rules

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@SapinderSingh Pull the latest code and also attach screenshot in this PR

**Comment by SapinderSingh** [comment]
@himanshusharma89 I have updated the master branch. But how can I update that code in my branch ?

**Comment by himanshusharma89** [comment]
> @himanshusharma89 I have updated the master branch. But how can I update that code in my branch ?

Yes, rebase your branch with master, after pulling the latest code in master.

**Comment by SapinderSingh** [comment]
> > @himanshusharma89 I have updated the master branch. But how can I update that code in my branch ?
> 
> Yes, rebase your branch with master, after pulling the latest code in master.

when I use, git rebase origin/master after using git fetch, It is showing merge conflicts

**Pull request merged**
