### PR TITLE
Fix: Issue #103, Added SafeArea in the the entire app

### LINKED ISSUE #103: Adding SafeArea widget on home.dart to avoid cutting off of screen
Currently there is no SafeArea widget because of which there is a possibility of drawer button getting cut by the top bar that show battery percentage on phones with smaller screen size.

### PR DESCRIPTION
**Pull request by believeInJha**
### Related Issue
- Fixes #103

### Proposed Changes
- Added SafeAree inside all pages

### Checklist
- [x] Tested
- [x] No Conflicts
- [x] Change In Code
- [ ] Change In Documentation
- [ ] Follows linting rules

### Screenshots
| PR| ScreenShot | 
|----------------|---------------|
| Before PR | Screenshot_1615827026
| |
| After PR   |  Screenshot_1615827026  |

### CODE REVIEW

**Comment by believeInJha** [comment]
Hey @himanshusharma89, kindly review this PR.

**Comment by himanshusharma89** [comment]
@believeInJha if you want to contribute, comment on the issue before creating a PR.

**Comment by believeInJha** [comment]
@himanshusharma89 really sorry to break the rules, it got totally out of my mind.

**Comment by himanshusharma89** [comment]
@believeInJha There is a total of 18 screens, some of them already have SafeArea. In your PR, there are a few files that don't require safearea as AppBar is already present, and some files are missing. Check the screens again.

**Comment by believeInJha** [comment]
Alright, thanks for the suggestion. I will make the changes.

**Comment by believeInJha** [comment]
Hey @himanshusharma89 I made the changes as you suggested.

**Review by himanshusharma89 — APPROVED** [review]

**Comment by himanshusharma89** [comment]
@believeInJha can you pull the latest code, to resolve the conflicts.

**Comment by believeInJha** [comment]
Okay, doing it.

**Review by believeInJha — COMMENTED** [review]
Reviewed all the changes.

**Review by himanshusharma89 — APPROVED** [review]

**Pull request merged**
