### PR TITLE
Added Named Routes and removed redundant code

### PR DESCRIPTION
**Pull request by SapinderSingh**
I have created named routes for all the screens with onGenerateRoute. I have removed some redundant code also.

### CODE REVIEW

**Comment by himanshusharma89** [comment]
@SapinderSingh You just need to create the constant and route page, you can remove all the other files and fixes. I'll create separate issues for that. For now, only constants and route page is required.

**Comment by SapinderSingh** [comment]
So should I close this pull request and create a new request after the edits ?

**Comment by SapinderSingh** [comment]
@himanshusharma89 By the way, I just reformatted some code with the help of commas and VS code's reformatter, removed some comments and a empty constructor and passed the route arguments in routes so that app can work like before. Then also I have to do the edits ?

**Comment by himanshusharma89** [comment]
> So should I close this pull request and create a new request after the edits ?

No need to close this PR. Only 2 files are required to be changed but in your PR total 12 files are changed and causing conflicts.

Do git pull, rebase the code to previous version and push the changes.

Note: Only route constants and route page files are required, nothing else.

**Comment by SapinderSingh** [comment]
> 
> 
> > So should I close this pull request and create a new request after the edits ?
> 
> No need to close this PR. Only 2 files are required to be changed but in your PR total 12 files are changed and causing conflicts.
> 
> Do git pull, rebase the code to previous version and push the changes.
> 
> Note: Only route constants and route page files are required, nothing else.

How can I rebase the code to previous version ?

**Comment by himanshusharma89** [comment]
@SapinderSingh I mentioned in my previous comment that:

> Do a git pull, rebase the code to the previous version and push the changes.

**Comment by SapinderSingh** [comment]
Now please check, I have removed all the other files.

**Pull request merged**
