### PR TITLE
modified contributng.md

### LINKED ISSUE #207: update contributing.md
Hi I would like to update contributing.md and add the following with proper steps-

Difference between git and github
Cloning a Repo
Creating a Branch and updating it locally as well as forked time to time
Creating a PR
Squashing Commits

### PR DESCRIPTION
**Pull request by khareyash05**
### Related Issue
- Fixes #207 

### Proposed Changes
Added items as mentioned in the issue

### Checklist
- [x] Tested
- [x] No Conflicts
- [ ] Change In Code
- [x] Change In Documentation
- [ ] Follows linting rules

### CODE REVIEW

**Comment by khareyash05** [comment]
@himanshusharma89 Created a PR Have a look

**Comment by himanshusharma89** [comment]
@khareyash05 Looks good, but can you do one thing, uniform the titles. The titles are all capitalised.

**Comment by khareyash05** [comment]
@himanshusharma89 Give me a minute

**Comment by khareyash05** [comment]
@himanshusharma89 Kindly re-review

**Review by himanshusharma89 — APPROVED** [review]

**Pull request merged**
